kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      nodeSelector:
        #<labelname>:value
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: spark-master
          image: $RL_HYPOTHESIS_1_DOCKER_IMAGE 
          command: ["/app/spark/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: N_WORKERS
              value: "$RL_HYPOTHESIS_1_N_WORKERS" 
            - name: PROJECT 
              value: "$RL_HYPOTHESIS_1_PROJECT"
            - name: ZONE
              value: "$RL_HYPOTHESIS_1_ZONE"
            - name: INSTANCE
              value: "$RL_HYPOTHESIS_1_INSTANCE"
            - name: CUDA_VISIBLE_DEVICES
              value: "-1"
            - name: RL_HYPOTHESIS_JOB_ID
              value: "$RL_HYPOTHESIS_1_JOB_ID"
            - name: RL_HYPOTHESIS_1_PROJECT
              value: "$RL_HYPOTHESIS_1_PROJECT"
            - name: RL_HYPOTHESIS_1_INSTANCE
              value: "$RL_HYPOTHESIS_1_INSTANCE"
            - name: RL_HYPOTHESIS_1_ZONE
              value: "$RL_HYPOTHESIS_1_ZONE"
            - name: RL_HYPOTHESIS_1_SERVICE_ACCOUNT_NAME
              value: "$RL_HYPOTHESIS_1_SERVICE_ACCOUNT_NAME"
          resources:
            requests:
              cpu: "100m"
              memory: "5Gi"
